# Airflow Configuration
airflow_url = "http://localhost:8080/api/v2"
airflow_username = "admin"
airflow_password = "admin"
DAG_ID = "ride_sharing_etl" 

# PostgreSQL Data Warehouse Configuration
postgres_host = "localhost"
postgres_db = "rides_warehouse"
postgres_user = "postgres"
postgres_password = "sqlbaz2003"
postgres_port = 5432

# MySQL OLTP Databases Configuration
mysql_host = "localhost"
mysql_user = "root"
mysql_password = "sqlbaz2003"
mysql_port = 3306

# Application Settings
app_title = "Ride Sharing DWH & BI Platform"
cache_ttl = 300